/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogos;

import java.awt.Color;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.JOptionPane;

/**
 *
 * @author IdlhDeveloper
 */
public class Password_Change extends javax.swing.JDialog {
Clases.Funciones Functions = new Clases.Funciones();
Clases.Consultations Consultations = new Clases.Consultations();
public int u;
    /**
     * Creates new form Password_Change
     */
    public Password_Change(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lbEstado.setVisible(false);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField4 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbEstado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cambiar Credenciales de Acceso");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(48, 10, 210, 14);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Por favor diligencie todos los campos");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(48, 25, 210, 14);

        jLabel4.setText("Contraseña Actual:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 80, 100, 14);

        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(20, 93, 150, 20);

        jLabel5.setText("Nueva Contraseña:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 120, 100, 14);

        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyReleased(evt);
            }
        });
        jPanel1.add(jPasswordField2);
        jPasswordField2.setBounds(20, 133, 150, 20);

        jLabel6.setText("Vuelva a escribir la contraseña:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 160, 160, 14);

        jPasswordField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField4KeyReleased(evt);
            }
        });
        jPanel1.add(jPasswordField4);
        jPasswordField4.setBounds(20, 173, 150, 20);

        jButton1.setText("Aceptar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(170, 210, 80, 22);

        jButton2.setText("Cerrar");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(260, 210, 70, 23);

        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Una contraseña segura contribuye");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 50, 180, 14);

        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText(" a evitar el acceso no autorizado.");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(18, 62, 280, 14);

        lbEstado.setForeground(new java.awt.Color(255, 0, 0));
        lbEstado.setText(".");
        jPanel1.add(lbEstado);
        lbEstado.setBounds(20, 195, 210, 14);

        jPanel2.setBackground(new java.awt.Color(16, 25, 16));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/male.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(302, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 340, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jPasswordField1.setText("");
        jPasswordField2.setText("");
        jPasswordField4.setText("");
        lbEstado.setText(".");
        lbEstado.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!jPasswordField1.getText().isEmpty()){
            if(!jPasswordField2.getText().isEmpty()){
            if(!jPasswordField4.getText().isEmpty()){
            if(jPasswordField2.getText().equals(jPasswordField4.getText()) || jPasswordField4.getText().equals(jPasswordField2.getText())){
            ActualizarPass(); 
            }else{
            lbEstado.setForeground(Color.red);    
            lbEstado.setVisible(true);
            lbEstado.setText("Las nuevas contraseñas no coinciden.");
            jPasswordField4.requestFocus();    
            } 
            }else{
            lbEstado.setForeground(Color.red);
            lbEstado.setVisible(true);
            lbEstado.setText("Diligencie su nueva contraseña 2 veces.");
            jPasswordField4.requestFocus(); 
            }
            }else{
            lbEstado.setForeground(Color.red);
            lbEstado.setVisible(true);
            lbEstado.setText("Diligencie su nueva contraseña 2 veces.");
            jPasswordField2.requestFocus(); 
            }
        }else{
            lbEstado.setForeground(Color.red);
            lbEstado.setVisible(true);
            lbEstado.setText("Ingrese su contraseña Actual.");
            jPasswordField1.requestFocus();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
        if(!jPasswordField1.getText().isEmpty()){
            lbEstado.setText("");
        }else{
            //--
        }
    }//GEN-LAST:event_jPasswordField1KeyReleased

    private void jPasswordField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyReleased
        // TODO add your handling code here:
        if(!jPasswordField2.getText().isEmpty()){
            lbEstado.setText("");
        }else{
            //--
        }
    }//GEN-LAST:event_jPasswordField2KeyReleased

    private void jPasswordField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField4KeyReleased
        // TODO add your handling code here:
        if(!jPasswordField4.getText().isEmpty()){
            lbEstado.setText("");
        }else{
            //--
        }
    }//GEN-LAST:event_jPasswordField4KeyReleased

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       jPasswordField1.setText("");
       jPasswordField2.setText("");
       jPasswordField4.setText("");
       lbEstado.setText(".");
       lbEstado.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Password_Change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Password_Change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Password_Change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Password_Change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                Password_Change dialog = new Password_Change(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
     private void ActualizarPass(){
        String password = new String(this.getPassword());
        String pa = new String(this.getPassword_Antiguo());
        String passwordFrom = null;
        String passwordAnt = null;
        int vV;
            try{
                MessageDigest MD5 = MessageDigest.getInstance("MD5");
                MessageDigest MD52 = MessageDigest.getInstance("MD5");
                byte[] tmp = password.getBytes();
                MD5.update(tmp);
                byte[] tmp2 = pa.getBytes();
                MD52.update(tmp2);
                String UserString = Integer.toString(u);
                passwordFrom = new String(Functions.byteArrToString(MD5.digest()).toCharArray());
                passwordAnt = new String(Functions.byteArrToString(MD52.digest()).toCharArray());
                Object CLogin[][] = Functions.RetornarDatos(Consultations.Count_Login2(passwordAnt));
                vV = Integer.parseInt(CLogin[0][0].toString());
                if(vV == 0){
                  lbEstado.setVisible(true);
                  lbEstado.setForeground(Color.red);
                  lbEstado.setText("La contraseña actual es incorrecta");  
                }else{
                if(Functions.executeUpdate(Consultations.UpdatePass(passwordFrom, UserString))==true){
                        lbEstado.setVisible(true);
                        lbEstado.setForeground(new java.awt.Color(4, 111, 8));
                        lbEstado.setText("La contraseña fue actualizada con exito");
                        jPasswordField1.setText("");
                        jPasswordField2.setText("");
                        jPasswordField4.setText("");
                }else{
                    JOptionPane.showMessageDialog(this, "Ha ocurrido un error inesperado, intentelo nuevamente", "Aplicacion", JOptionPane.ERROR_MESSAGE);
                }   
                }
          } catch (NoSuchAlgorithmException ex) {
              JOptionPane.showMessageDialog(null, ex.getMessage());
          }
    }
    public char[] getPassword(){
        return this.jPasswordField2.getPassword();
    }
    public char[] getPassword_Antiguo(){
        return this.jPasswordField1.getPassword();

    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JLabel lbEstado;
    // End of variables declaration//GEN-END:variables
}
